version: "3.6"

services:
  api: 
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/apiRails
    depends_on:
      - database
    
  frontend:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - node_modules:/clientNode/node_modules
  database:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password

volumes:
  node_modules:
    