version: "3.7"

services:
  api: 
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/apiRails
    depends_on:
      - database
  
  database:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password
    